import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import NextThemeProvider from "./providers/NextThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
     suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className=" text-foreground min-h-full flex flex-col bg-linear-to-r from-pink-100 via-mauve-200 to-mauve-300
      dark:bg-linear-to-r dark:from-mauve-800 dark:via-mauve-700 dark:to-mauve-900">
        <NextThemeProvider>
            <Navbar></Navbar>
          {children}
        <Toaster position="top-right" />
        </NextThemeProvider>
        
      </body>
    </html>
  );
}
